# Generated by Django 3.2.9 on 2021-11-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
